### ISSUE TITLE
Running run_test.py results in the error testKeyError: 'articulation'.

### ISSUE THREAD

**Issue by Orion520** [UT-Austin-RPL/Ditto#13]
Error executing job with overrides: ['experiment=Ditto_s2m', 'trainer.resume_from_checkpoint=/home/lqc/Ditto/data/Ditto_s2m-18-43-30/checkpoints/last.ckpt']
Traceback (most recent call last):
  File "run_test.py", line 34, in main
    return test(config)
  File "/home/lqc/Ditto/src/test.py", line 89, in test
    trainer.test(model=model, datamodule=datamodule)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 906, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1270, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating
    self._results = trainer.run_stage()
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1281, in run_stage
    return self._run_evaluate()
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1329, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 130, in on_run_end
    self._evaluation_epoch_end(outputs)
  File "/home/lqc/anaconda3/envs/Ditto/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 230, in _evaluation_epoch_end
    model.test_epoch_end(outputs)
  File "/home/lqc/Ditto/src/models/geo_art_model_v0.py", line 498, in test_epoch_end
    for k, v in result["articulation"].items():
KeyError: 'articulation'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Orion520** [comment]
Issue has solved. Possible causes:
In training,
1) half the learning rate when changing the batch size.
2) trainer max epoch > callbacks: early_stopping:patience.
