### ISSUE TITLE
预训练报错：ImportError: Encountered error: `numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject` 

### ISSUE THREAD

**Issue by Lozumi** [UT-Austin-RPL/Ditto#14]
您好，尝试复现您团队的代码，遇到报错。
系统环境：
```bash
Linux test-NF5 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:0D:00.0 Off |                  Off |
| 39%   55C    P0            194W /  450W |   13305MiB /  24564MiB |     44%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:37:00.0 Off |                  Off |
| 36%   56C    P0            177W /  450W |   13305MiB /  24564MiB |     58%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        Off |   00000000:4C:00.0 Off |                  Off |
| 30%   54C    P0            176W /  450W |   13321MiB /  24564MiB |     56%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 4090        Off |   00000000:61:00.0 Off |                  Off |
| 36%   57C    P0            185W /  450W |   13277MiB /  24564MiB |     66%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA GeForce RTX 4090        Off |   00000000:85:00.0 Off |                  Off |
| 43%   58C    P0            198W /  450W |   13285MiB /  24564MiB |     48%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA GeForce RTX 4090        Off |   00000000:B1:00.0 Off |                  Off |
| 32%   57C    P0            181W /  450W |   13281MiB /  24564MiB |     51%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA GeForce RTX 4090        Off |   00000000:C7:00.0 Off |                  Off |
| 30%   52C    P0            190W /  450W |   13285MiB /  24564MiB |     47%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA GeForce RTX 4090        Off |   00000000:DD:00.0 Off |                  Off |
| 32%   57C    P0            195W /  450W |   13297MiB /  24564MiB |     47%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

```
Conda环境配置：
```bash
name: Ditto

channels:
  - pytorch
  - conda-forge
  - pyg

dependencies:
  - python=3.8
  - pip<24.1
  - cudatoolkit=11.3
  - pytorch=1.10.2=py3.8_cuda11.3_cudnn8.2.0_0
  - torchvision
  - pytorch-scatter
  - pip:
      - -r requirements.txt

variables:
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: "True"

```

requirements.txt
```bash
# --------- pytorch --------- #
pytorch-lightning==1.5.4
torchmetrics==0.4.1
setuptools==59.5.0

# --------- hydra --------- #
hydra-core==1.1.0.rc1
hydra-colorlog==1.1.0.dev1
hydra-optuna-sweeper==1.1.0.dev2
# hydra-ax-sweeper==1.1.0
# hydra-ray-launcher==0.1.2
# hydra-submitit-launcher==1.1.0

# --------- loggers --------- #
wandb>=0.10.30
# neptune-client
# mlflow
# comet-ml
# torch_tb_profiler

# --------- linters --------- #
pre-commit
black
isort
flake8

# --------- others --------- #
jupyterlab
python-dotenv
rich
pytest
sh
scikit-learn
seaborn
pudb
# dvc

# --------- Ditto --------- #
open3d==0.12.0
pybullet==2.7.9
trimesh
cython
pykdtree
```
执行ConvONet初始化脚本无error，用s2m预训练模型，遇到报错如下：
```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_test.py", line 34, in main
    return test(config)
  File "/home/robotrl/Ditto/src/test.py", line 40, in test
    model: LightningModule = hydra.utils.instantiate(config.model)
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 240, in instantiate_node
    target = _resolve_target(node.get(_Keys.TARGET))
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 104, in _resolve_target
    return _locate(target)
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/site-packages/hydra/_internal/utils.py", line 577, in _locate
    raise ImportError(
ImportError: Encountered error: `numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject` when loading module 'src.models.geo_art_model_v0.GeoArtModelV0'
```
尝试修改numpy版本为1.20,1.21，均报类似错误。
麻烦指正！可邮箱联系，lozumi@qq.com。

**Comment by Steve-Tod** [comment]
Try `pip install numpy==1.19.5`?

**Comment by Lozumi** [comment]
您好，修改numpy为1.19.5后，仍然报类似错误
```bash
Error executing job with overrides: ['experiment=Ditto_s2m', 'trainer.resume_from_checkpoint=/home/robotrl/Ditto/models/Ditto_s2m.ckpt']
Traceback (most recent call last):
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/site-packages/hydra/_internal/utils.py", line 575, in _locate
    import_module(mod)
  File "/home/robotrl/.conda/envs/Ditto/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/robotrl/Ditto/src/models/geo_art_model_v0.py", line 14, in <module>
    from src.models.modules import create_network
  File "/home/robotrl/Ditto/src/models/modules/__init__.py", line 1, in <module>
    from src.third_party.ConvONets.config import get_model as ConvONets
  File "/home/robotrl/Ditto/src/third_party/ConvONets/config.py", line 3, in <module>
    from src.third_party.ConvONets import conv_onet
  File "/home/robotrl/Ditto/src/third_party/ConvONets/conv_onet/__init__.py", line 1, in <module>
    from src.third_party.ConvONets.conv_onet import config, generation_two_stage, models
  File "/home/robotrl/Ditto/src/third_party/ConvONets/conv_onet/config.py", line 4, in <module>
    from src.third_party.ConvONets.conv_onet import generation_two_stage as generation
  File "/home/robotrl/Ditto/src/third_party/ConvONets/conv_onet/generation_two_stage.py", line 8, in <module>
    from src.third_party.ConvONets.common import (
  File "/home/robotrl/Ditto/src/third_party/ConvONets/common.py", line 6, in <module>
    from pykdtree.kdtree import KDTree
  File "pykdtree/kdtree.pyx", line 1, in init pykdtree.kdtree
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

**Comment by Lozumi** [comment]
您好，经查问题出现在pykdtree安装了1.3.2版本，对numpy版本有要求，pykdtree降级到1.3.0后正常运行。
conda未能检测到兼容性问题，我在numpy==1.9.5和pykdtree==1.3.2版本下可正常运行，建议您补充requirements.txt~

**Comment by Steve-Tod** [comment]
> 您好，经查问题出现在pykdtree安装了1.3.2版本，对numpy版本有要求，pykdtree降级到1.3.0后正常运行。 conda未能检测到兼容性问题，我在numpy==1.9.5和pykdtree==1.3.2版本下可正常运行，建议您补充requirements.txt~

Thanks!
